name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: openpolicyagent/opa:edge-static-debug

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Quay.io
      run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

    - name: Set image tag
      id: vars
      run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag quay.io/rh-ee-gpasten/test1/prueba:${{ steps.vars.outputs.tag }}

    - name: Push to Quay.io
      run: docker push quay.io/rh-ee-gpasten/test1/prueba:${{ steps.vars.outputs.tag }}

    - name: curl
      run: curl -v https://rickandmortyapi.com/api/character/264

      
